// Serialize a BuiltCity into a committed CityData module under src/data/cities.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { encodeBytes, type CityData, type CityNamedPlace } from '../../src/data/cityData';
import type { CouncilProfile, TransportRoute } from '../../src/sim/map/types';
import type { BuiltCity } from './buildCityFromOsm';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(HERE, '../../src/data/cities');

const r2 = (v: number): number => Math.round(v * 100) / 100;
const r3 = (v: number): number => Math.round(v * 1000) / 1000;

function roundRoutes(routes: TransportRoute[]): TransportRoute[] {
  return routes.map((r) => ({ kind: r.kind, pts: r.pts.map(([x, y]) => [r2(x), r2(y)] as [number, number]) }));
}
function roundCouncils(councils: CouncilProfile[]): CouncilProfile[] {
  return councils.map((c) => ({ ...c, affluence: r3(c.affluence), ambition: r3(c.ambition) }));
}

export function toCityData(
  built: BuiltCity,
  meta: { id: string; name: string; tagline: string; fabric?: 'london' | 'paris' },
): CityData {
  const m = built.map;
  return {
    id: meta.id,
    name: meta.name,
    tagline: meta.tagline,
    ...(meta.fabric && meta.fabric !== 'london' ? { fabric: meta.fabric } : {}),
    width: m.width,
    height: m.height,
    terrain: encodeBytes(m.terrain),
    zone: encodeBytes(m.zone),
    council: encodeBytes(m.council),
    road: encodeBytes(m.road),
    landmark: encodeBytes(m.landmark ?? new Uint8Array(m.width * m.height)),
    flags: encodeBytes(m.flags ?? new Uint8Array(m.width * m.height)),
    routes: roundRoutes(m.routes ?? []),
    councils: roundCouncils(m.councils),
    named: built.named as CityNamedPlace[],
    attribution: '© OpenStreetMap contributors',
  };
}

export function writeCityModule(data: CityData): string {
  mkdirSync(OUT_DIR, { recursive: true });
  const constName = data.id.toUpperCase().replace(/[^A-Z0-9]/g, '_') + '_CITY';
  const file = join(OUT_DIR, `${data.id}.ts`);
  const body = `// GENERATED by tools/buildCity.ts — do not edit by hand.
// Map data © OpenStreetMap contributors (ODbL).
import type { CityData } from '../cityData';

export const ${constName}: CityData = ${serialize(data)};
`;
  writeFileSync(file, body);
  return file;
}

/** Stringify with the giant base64 rasters on their own lines for sane diffs. */
function serialize(d: CityData): string {
  const lines = [
    '{',
    `  id: ${JSON.stringify(d.id)},`,
    `  name: ${JSON.stringify(d.name)},`,
    `  tagline: ${JSON.stringify(d.tagline)},`,
    `  width: ${d.width},`,
    `  height: ${d.height},`,
    `  terrain: ${JSON.stringify(d.terrain)},`,
    `  zone: ${JSON.stringify(d.zone)},`,
    `  council: ${JSON.stringify(d.council)},`,
    `  road: ${JSON.stringify(d.road)},`,
    `  landmark: ${JSON.stringify(d.landmark)},`,
    `  flags: ${JSON.stringify(d.flags)},`,
    `  routes: ${JSON.stringify(d.routes)},`,
    `  councils: ${JSON.stringify(d.councils)},`,
    `  named: ${JSON.stringify(d.named)},`,
    ...(d.fabric ? [`  fabric: ${JSON.stringify(d.fabric)},`] : []),
    `  attribution: ${JSON.stringify(d.attribution)},`,
    '}',
  ];
  return lines.join('\n');
}
